version: "3.7"

networks:
  kafka_network:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks: 
      - kafka_network

  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - 9092:9092
    networks: 
      - kafka_network
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1  
    depends_on:
      - zookeeper
    restart: always

